{{- if .Values.microServices }}
{{- range $key, $value := .Values.microServices }} 

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ $key }}
  labels:
    app: {{ $key }}
    version: v1
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $key }}
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app: {{ $key }}
        version: v1
    spec:
      containers:
        - image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: Always           
          name: {{ $key }}
          ports:
          - containerPort: {{ $value.containerPort }}   
---
{{- end }}
{{- end }}
